//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMC_Donation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class requestitem
    {
        public int id { get; set; }
        [Required(ErrorMessage = "required")]
        public int sender_id { get; set; }
        [Required(ErrorMessage = "required")]
        public int receiver_id { get; set; }
        [Required(ErrorMessage = "required")]
        public int item_id { get; set; }
        [Required(ErrorMessage = "required")]
        public Nullable<int> approved_status { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
        public Nullable<int> status { get; set; }
    }
}
